database:
  technology: postgres
  # server: 100.105.141.99 ## ub
  server: localhost 
  port: 5432
  ssl: false
  schema: tally_incremental_db
  username: satyam
  password: satyam52
  loadmethod: insert
tally:
  definition: tally-export-config.yaml
  # server: 100.77.107.9 ### winvm
  # company: ABC-24 -DEC

  server: 100.77.107.9 ## winvm
  company: ABC-24 -DEC
  # company: ABC-24 -DEC - (from 1-Apr-2025)

  # server: 172.16.0.47
  # company: Dummy

  port: 9000
  fromdate: '2025-08-01'
  todate: '2026-03-31'
  sync: full
  frequency: 5
